# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 620e40cf0e9adc281b1a481800bcbe75b68b1ff14aeab439b0e924121a5d7c14ba25c02734b5784266dd20caaed68123a5cad04333d43380f6d9326479e86f07

test:
  secret_key_base: 6a0e3d24a26c5ad376acb1d6e58d15927055b6d5a66009254cd573f715d33a716d8c728eea212be439ad4bedbc1f625ccb057965774ad70c434c2053b4502cea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
